# Generated by Django 5.1 on 2024-09-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slacktoken_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slacktoken',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
